/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_axvoice_WRAP_H_
#define SWIG_axvoice_WRAP_H_

class SwigDirector_AxVoiceMessage : public AxVoiceMessage, public Swig::Director {

public:
    SwigDirector_AxVoiceMessage();
    virtual AxVoiceMessage::Type getType() const;
    virtual unsigned int getVoiceID() const;
    virtual int getParamCounts() const;
    virtual char const *getParam(int index) const;

    typedef int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef char * (SWIGSTDCALL* SWIG_Callback3_t)(int);
    void swig_connect_director(SWIG_Callback0_t callbackgetType, SWIG_Callback1_t callbackgetVoiceID, SWIG_Callback2_t callbackgetParamCounts, SWIG_Callback3_t callbackgetParam);

private:
    SWIG_Callback0_t swig_callbackgetType;
    SWIG_Callback1_t swig_callbackgetVoiceID;
    SWIG_Callback2_t swig_callbackgetParamCounts;
    SWIG_Callback3_t swig_callbackgetParam;
    void swig_init_callbacks();
};

class SwigDirector_AxVoiceCallback : public AxVoiceCallback, public Swig::Director {

public:
    SwigDirector_AxVoiceCallback();
    virtual ~SwigDirector_AxVoiceCallback();
    virtual void onMessage(AxVoiceMessage const *message);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackonMessage);

private:
    SWIG_Callback0_t swig_callbackonMessage;
    void swig_init_callbacks();
};


#endif
