/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace com.axia {

class axvoicePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="SWIGRegisterExceptionCallbacks_axvoice")]
    public static extern void SWIGRegisterExceptionCallbacks_axvoice(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_axvoice")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_axvoice(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_axvoice(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_axvoice(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(axvoicePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(axvoicePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="SWIGRegisterStringCallback_axvoice")]
    public static extern void SWIGRegisterStringCallback_axvoice(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_axvoice(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static axvoicePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_Init")]
  public static extern bool AxVoice_Init(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_BeginRecord")]
  public static extern uint AxVoice_BeginRecord();

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_CompleteRecord")]
  public static extern void AxVoice_CompleteRecord(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_UploadVoice")]
  public static extern void AxVoice_UploadVoice(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_CreatVoice")]
  public static extern uint AxVoice_CreatVoice(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_DownloadVoice")]
  public static extern void AxVoice_DownloadVoice(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_PlayVoice")]
  public static extern void AxVoice_PlayVoice(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_StopVoice")]
  public static extern void AxVoice_StopVoice();

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceMessage_getType")]
  public static extern int AxVoiceMessage_getType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceMessage_getVoiceID")]
  public static extern uint AxVoiceMessage_getVoiceID(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceMessage_getParamCounts")]
  public static extern int AxVoiceMessage_getParamCounts(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceMessage_getParam")]
  public static extern string AxVoiceMessage_getParam(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_new_AxVoiceMessage")]
  public static extern global::System.IntPtr new_AxVoiceMessage();

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_delete_AxVoiceMessage")]
  public static extern void delete_AxVoiceMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceMessage_director_connect")]
  public static extern void AxVoiceMessage_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, AxVoiceMessage.SwigDelegateAxVoiceMessage_0 delegate0, AxVoiceMessage.SwigDelegateAxVoiceMessage_1 delegate1, AxVoiceMessage.SwigDelegateAxVoiceMessage_2 delegate2, AxVoiceMessage.SwigDelegateAxVoiceMessage_3 delegate3);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_delete_AxVoiceCallback")]
  public static extern void delete_AxVoiceCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceCallback_onMessage")]
  public static extern void AxVoiceCallback_onMessage(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_new_AxVoiceCallback")]
  public static extern global::System.IntPtr new_AxVoiceCallback();

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoiceCallback_director_connect")]
  public static extern void AxVoiceCallback_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, AxVoiceCallback.SwigDelegateAxVoiceCallback_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("axvoice", EntryPoint="CSharp_AxVoice_DispatchMessage")]
  public static extern void AxVoice_DispatchMessage(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
